### ISSUE TITLE
hello please help me

### ISSUE THREAD

**Issue by hannescam** [gogakoreli/snake#1]
i want to create a snake field that is 64*32 but if i do that in macros.h i instantly die
please help

**Comment by hannescam** [comment]
i have found the problem in main.cpp in is_game_end() map_height and map_width were swapped
i will open a pull request

**Comment by gogakoreli** [comment]
@hannescam That's correct, please send the PR for the fix and I will be more than glad to merge it!

**Comment by hannescam** [comment]
i opend a pull request: https://github.com/gogakoreli/snake/pull/2

**Comment by gogakoreli** [comment]
Looks good, merged! Thank you for finding the issue and opening the pr for it.
